### ISSUE TITLE
Invalid texture error

### ISSUE THREAD

**Issue by CrayolaEater** [clayjohn/godot-volumetric-cloud-demo-v2#1]
I got your example repo and just changed the source of the scripts.
The clouds render but I m getting this error in console
![image](https://github.com/clayjohn/godot-volumetric-cloud-demo-v2/assets/38570835/37fee8ec-ab0f-47dd-a8b2-15c028ccf9fb)

Here is the project structure (project too big to upload)
![image](https://github.com/clayjohn/godot-volumetric-cloud-demo-v2/assets/38570835/9857d656-85f0-4abb-87f1-c3efe6c19027)

I also changed the path in code to coresspond to the absolute path of the resource:
![image](https://github.com/clayjohn/godot-volumetric-cloud-demo-v2/assets/38570835/7accb1d8-55d7-483c-973c-8d6d6d1d7dcf)

**Comment by clayjohn** [comment]
Hi, those errors are harmless and are caused by a Godot bug in 4.2.x that has been fixed for 4.3 (see https://github.com/godotengine/godot/pull/87541).

They are caused by the `rd_rid` being saved into the .tres file even though they shouldn't be saved. 

To get rid of them completely you need to use Godot 4.3 (dev3 or newer) and manually delete the `rd_rid`s that have been saved into the .tres files

**Comment by CrayolaEater** [comment]
Okay, thanks for the info

**Comment by CrayolaEater** [comment]
Coming back after the 4.3 launch, the error still persists

**Comment by clayjohn** [comment]
Did you remember to manually delete the `rd_rid`s that were saved into the .tres file as I suggested above?

**Comment by CrayolaEater** [comment]
> Did you remember to manually delete the `rd_rid`s that were saved into the .tres file as I suggested above?

Ah, forgot to do that. Now works thanks!
